include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports

analyzer:
  plugins:
    - dart_code_metrics

  exclude:
    - "**/*.mocks.dart"
    - "**/*.gr.dart"
    - "test/generated/**"
    - "lib/gen/**"
    - "lib/di.config.dart"

  errors:
    always_use_package_imports: ignore
    avoid_relative_lib_imports: ignore
    deprecated_member_use_from_same_package: ignore

dart_code_metrics:
  rules:
    avoid-banned-imports:
      severity: error
      entries:
        - paths: [".*/models/.+\\.dart"]
          deny: [".*/(data|services|widgets|screens|ui|l10n)/.*"]
          message: "Do not import data|services|widgets|screens|ui|l10n from models"

        - paths: [".*/data/.+\\.dart"]
          deny: [".*/(services|widgets|screens|ui|l10n)/.*"]
          message: "Do not import services|widgets|screens|ui|l10n from data"

        - paths: [".*/services/.+\\.dart"]
          deny: [".*/(widgets|screens|ui|l10n)/.*"]
          message: "Do not import widgets|screens|ui|l10n from services"

        - paths: [".*/widgets/.+\\.dart"]
          deny: [".*/screens/.*"]
          message: "Do not import screens from widgets"

        - paths: [".*/ui/.+\\.dart"]
          deny: [".*/features/.*"]
          message: "Do not import features from ui"

  rules-exclude:
    - "**/*.gr.dart"
    - "**/generated_plugin_registrant.dart"
