name: ava
description: Ava Via CEP Flutter test
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  auto_route: ^7.7.0
  bloc: ^8.1.2
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  dfunc: ^0.9.0
  drift: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.5.0
  meta: ^1.9.1
  nested: ^1.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  rxdart: ^0.27.7
  search_cep: ^4.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.2.0
  freezed: ^2.4.1
  injectable_generator: ^2.1.6
  drift_dev: ^2.10.0
  json_serializable: ^6.7.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900
